/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.todo;
import java.awt.event.ActionEvent;
import java.util.ArrayList;
import javax.swing.text.DateFormatter;
import com.toedter.calendar.JDateChooser;
import java.awt.GridBagConstraints;
import java.awt.GridLayout;
import java.awt.Insets;
import java.sql.Time;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.DayOfWeek;
import java.time.Instant;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.Month;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.time.format.TextStyle;
import java.util.Date;
import java.util.Locale;import javax.swing.BoxLayout;
import javax.swing.JComboBox;

import javax.swing.JOptionPane;
/**
 *
 * @author jleeg
 */
public class Input extends javax.swing.JFrame {
    private  JComboBox<String> jComboBox1;

    
    private ArrayList<String> tasks = new ArrayList<>();

    /**
     * Creates new form InputFrame
     */
    public Input() {
        initComponents();
        //jDateChooser3 = new com.toedter.calendar.JDateChooser();
        //timePicker = new com.github.lgooddatepicker.components.TimePicker();
        jComboBox1 = new JComboBox<>(new String[]{"AM", "PM"});
        //jPanel1.setLayout(new java.awt.GridBagLayout());
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.gridx = 7;
        gbc.gridy = 6;
        gbc.anchor = GridBagConstraints.NORTHWEST;
        gbc.insets = new Insets(10, 0, 0, 0);
        jPanel1.add(jComboBox1, gbc);
        getContentPane().setBackground(new java.awt.Color(245, 245, 220));

        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jPanel1 = new javax.swing.JPanel();
        addtask = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        descTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        date = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        submitBtn = new javax.swing.JButton();
        timed = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Task");
        setBackground(new java.awt.Color(30, 31, 32));

        jPanel1.setBackground(new java.awt.Color(245, 245, 220));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        addtask.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addtask.setForeground(new java.awt.Color(0, 51, 51));
        addtask.setText("Add Task");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 11, 0, 0);
        jPanel1.add(addtask, gridBagConstraints);

        jLabel2.setForeground(new java.awt.Color(0, 51, 51));
        jLabel2.setText("Task Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 11, 0, 0);
        jPanel1.add(jLabel2, gridBagConstraints);

        nameTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.ipadx = 68;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 6, 0, 0);
        jPanel1.add(nameTextField, gridBagConstraints);

        jLabel4.setForeground(new java.awt.Color(0, 51, 51));
        jLabel4.setText("Task Description");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 11, 0, 0);
        jPanel1.add(jLabel4, gridBagConstraints);

        descTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        descTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descTextFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 14;
        gridBagConstraints.ipadx = 150;
        gridBagConstraints.ipady = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 6, 0, 0);
        jPanel1.add(descTextField, gridBagConstraints);

        jLabel5.setForeground(new java.awt.Color(0, 51, 51));
        jLabel5.setText("Date");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 11, 0, 0);
        jPanel1.add(jLabel5, gridBagConstraints);

        date.setForeground(new java.awt.Color(153, 153, 153));
        date.setText("dd-mm-yyyy");
        date.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dateFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                dateFocusLost(evt);
            }
        });
        date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateActionPerformed(evt);
            }
        });
        date.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dateKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 37;
        gridBagConstraints.ipady = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 6, 0, 0);
        jPanel1.add(date, gridBagConstraints);

        jLabel6.setForeground(new java.awt.Color(0, 51, 51));
        jLabel6.setText("Time");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 14, 0, 0);
        jPanel1.add(jLabel6, gridBagConstraints);

        submitBtn.setBackground(new java.awt.Color(0, 102, 102));
        submitBtn.setForeground(new java.awt.Color(255, 255, 255));
        submitBtn.setText("Submit");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.ipadx = 38;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(38, 0, 26, 0);
        jPanel1.add(submitBtn, gridBagConstraints);

        timed.setForeground(new java.awt.Color(153, 153, 153));
        timed.setText("hh:mm");
        timed.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                timedFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                timedFocusLost(evt);
            }
        });
        timed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timedActionPerformed(evt);
            }
        });
        timed.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                timedKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 13;
        gridBagConstraints.ipady = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 6, 0, 31);
        jPanel1.add(timed, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed

        tasks.add(nameTextField.getText());
        tasks.add(descTextField.getText());
        
        dateActionPerformed(evt);
        timedActionPerformed(evt);
        MaintoDo.toDoFrame.addTask(tasks);
        this.dispose();
    
    }//GEN-LAST:event_submitBtnActionPerformed

    private void descTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descTextFieldActionPerformed
        String desc = descTextField.getText();
        tasks.add(desc);
    }//GEN-LAST:event_descTextFieldActionPerformed

    private void nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextFieldActionPerformed
        String name = nameTextField.getText();
        tasks.add(name);
    }//GEN-LAST:event_nameTextFieldActionPerformed

    private void dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateActionPerformed
        // TODO add your handling code here:
        String datestr = date.getText();
        DateTimeFormatter format = DateTimeFormatter.ofPattern("dd-MM-yyyy");
        

        SimpleDateFormat dateformat = new SimpleDateFormat("dd-MM-yyyy");
        
        try{
            Date date = dateformat.parse(datestr);
            LocalDate ldate = Instant.ofEpochMilli(date.getTime()).atZone(ZoneId.systemDefault()).toLocalDate();
            DayOfWeek dow = ldate.getDayOfWeek();
            Integer dom = ldate.getDayOfMonth();
            Month Month = ldate.getMonth();
            String month = Month.getDisplayName(TextStyle.SHORT, Locale.ENGLISH);
            String formatted = dateformat.format(date);
            String dayofweek = dow.getDisplayName(TextStyle.SHORT, Locale.ENGLISH);
            //tasks.add(dayofweek +" "+ dom + ","+ month);
            tasks.add(formatted);
        } catch(ParseException e){
            JOptionPane.showMessageDialog(this, "Invalid date");          
        }
    }//GEN-LAST:event_dateActionPerformed

    private void dateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dateFocusGained
        // TODO add your handling code here:
        if(date.getText().equals("dd-mm-yyyy")){
            date.setCaretPosition(0);
        }
    }//GEN-LAST:event_dateFocusGained

    private void dateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dateFocusLost
        // TODO add your handling code here:
        if(date.getText().equals("")){
            date.setForeground(new java.awt.Color(86, 86, 86));
            date.setCaretPosition(0);
            date.setText("dd-mm-yyyy");
        }
    }//GEN-LAST:event_dateFocusLost

    private void dateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dateKeyPressed
        // TODO add your handling code here:
        if(date.getText().equals("dd-mm-yyyy")){
            date.setForeground(new java.awt.Color(0, 0, 0));
            date.setCaretPosition(0);
            date.setText(null);
        }
    }//GEN-LAST:event_dateKeyPressed

    private void timedKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_timedKeyPressed
        // TODO add your handling code here:
        if(timed.getText().equals("hh:mm")){
            timed.setForeground(new java.awt.Color(0, 0, 0));
            timed.setCaretPosition(0);
            timed.setText(null);
        }
    }//GEN-LAST:event_timedKeyPressed

    private void timedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timedActionPerformed
        // TODO add your handling code here:
        String timestr = timed.getText();
        String ampm = (String)jComboBox1.getSelectedItem();
        String combined = timestr + " " + ampm;
        DateTimeFormatter inputformat = DateTimeFormatter.ofPattern("h:mm a");
        DateTimeFormatter outputformat = DateTimeFormatter.ofPattern("h:mm a");
        try{
            LocalTime timed = LocalTime.parse(combined, inputformat);
            String format = timed.format(outputformat);
            tasks.add(format);

        } catch(DateTimeParseException e){
            JOptionPane.showMessageDialog(this, "Invalid ");

        }
    }//GEN-LAST:event_timedActionPerformed

    private void timedFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_timedFocusLost
        // TODO add your handling code here:
        if(timed.getText().equals("")){
            timed.setForeground(new java.awt.Color(86, 86, 86));
            timed.setText("hh:mm");
        }
    }//GEN-LAST:event_timedFocusLost

    private void timedFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_timedFocusGained
        // TODO add your handling code here:
        if(timed.getText().equals("hh:mm")){
            timed.setCaretPosition(0);
        }
    }//GEN-LAST:event_timedFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Input.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Input.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Input.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Input.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
       // System.out.println(tasks.get(2));
        //</editor-fold>
        //</editor-fold>
       // System.out.println(tasks.get(2));
        //</editor-fold>
        //</editor-fold>
       // System.out.println(tasks.get(2));
        //</editor-fold>
        //</editor-fold>
       // System.out.println(tasks.get(2));

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Input().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addtask;
    private javax.swing.JTextField date;
    private javax.swing.JTextField descTextField;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JButton submitBtn;
    javax.swing.JTextField timed;
    // End of variables declaration//GEN-END:variables
}
